# train_yolov8m_p6_repro.yaml
# Reproduce a YOLOv8m-P6 baseline on 1280x1280 with 5 classes and common augmentations.
# Use with: yolo detect train cfg=train_yolov8m_p6_repro.yaml

mode: train
model: yolov8m-p6.pt         # P6 backbone/head; pretrained on COCO
data: D:/Hoogen/Thesis/MADS_thesis_equivariance/data/processed/images/dataset.yaml

# Core training
imgsz: 1280
epochs: 100
batch: 16
device: 0
workers: 8
seed: 42

# Color space
hsv_h: 0.015     # hue shift
hsv_s: 0.7       # saturation shift
hsv_v: 0.4       # brightness/value shift

# Geometry
degrees: 5.0     # small rotations
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0

# Flips
fliplr: 0.5
flipud: 0.0

# Mixers
mosaic: 1.0
mixup: 0.1       # enable light mixup (0.0 disables)
cutmix: 0.0
copy_paste: 0.0

# Extras
auto_augment: randaugment    # RandAugment policy
erasing: 0.4                 # Random Erasing prob (applies when supported)

# (Optional) If you truly want to initialize a P6 model using v8m (P5) weights,
# you can switch to this combo instead (not generally recommended):
# model: yolov8m-p6.yaml
# pretrained: yolov8m.pt
